spring:
  application:
    name: aspire-ai-backend

  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

  datasource:
    url: ${DB_URL:jdbc:postgresql://db.omjclmgvdkvbnvijzrwg.supabase.co:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:rediss://default:gQAAAAAAAZcXAAIgcDI1OGY0NmE1ZWUzMzU0MDFlOTViOTliOWEyYTQ0NmRmNw@ethical-fowl-104215.upstash.io:6379}

  ai:
    google:
      project-id: ${GOOGLE_GENAI_PROJECT_ID:}
      location: ${GOOGLE_GENAI_LOCATION:us-central1}
      api-key: ${GOOGLE_GENAI_API_KEY:}

      genai:
        api-key: ${GOOGLE_GENAI_API_KEY:}
        project-id: ${GOOGLE_GENAI_PROJECT_ID:}
        location: ${GOOGLE_GENAI_LOCATION:us-central1}

        chat:
          options:
            model: gemini-2.5-flash

        embedding:
          api-key: ${GOOGLE_GENAI_API_KEY:}
          project-id: ${GOOGLE_GENAI_PROJECT_ID:}
          location: ${GOOGLE_GENAI_LOCATION:us-central1}

          text:
            options:
              model: gemini-embedding-2
              dimensions: 768

    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 768
        distance-type: cosine_distance
        index-type: hnsw

        jdbc-url: ${SPRING_AI_VECTORSTORE_PGVECTOR_JDBC_URL:jdbc:postgresql://db.omjclmgvdkvbnvijzrwg.supabase.co:5432/postgres}
        username: ${SPRING_AI_VECTORSTORE_PGVECTOR_USERNAME:postgres}
        password: ${SPRING_AI_VECTORSTORE_PGVECTOR_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  cache:
    type: redis

    redis:
      time-to-live: 21600000

security:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000

server:
  address: 0.0.0.0
  port: ${PORT:8080}

github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN:}